### ISSUE TITLE
How to create linstor controller

### ISSUE THREAD

**Issue by selvakumarnms** [LINBIT/linstor-external-provisioner#6]
HI, I have been trying to install flex volume plugin and external linstor provisioner. As part of this I have been asked to configure the controller like below, 
controllers: "192.168.10.10:8080,172.0.0.1:3366"

 how to install DRBD controllers ? I use openshift to manage kubernetes node.
your help will be greatly appreciated

Thanks

**Comment by selvakumarnms** [comment]
Also I have referred the as per examples folder and I use linstor-external-provisioner process , and the logs it is shown as  Failed to provision volume for claim "default/example-linstor-volume" with StorageClass "example-linstor-sc": exec: "linstor": executable file not found in $PATH:
Kindly help this.

**Comment by selvakumarnms** [comment]
Attached the complete logs
golinstor: 2018/10/08 04:49:01 linstor.go:265: ("default-example-linstor-volume"): linstor -m --controllers 192.168.10.10:8080,172.0.0.1:3366 resource-definition list
E1008 04:49:01.389959    5411 controller.go:1074] Failed to provision volume for claim "default/example-linstor-volume" with StorageClass "example-linstor-sc": exec: "linstor": executable file not found in $PATH:
I1008 04:49:01.390211    5411 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"example-linstor-volume", UID:"822f5ebe-caa4-11e8-a6cd-52540023de97", APIVersion:"v1", ResourceVersion:"749092", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass "example-linstor-sc": exec: "linstor": executable file not found in $PATH:
I1008 04:49:01.390225    5411 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"example-linstor-volume", UID:"822f5ebe-caa4-11e8-a6cd-52540023de97", APIVersion:"v1", ResourceVersion:"749092", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/example-linstor-volume"
I1008 04:49:31.608293    5411 leaderelection.go:204] stopped trying to renew lease to provision for pvc default/example-linstor-volume, timeout reached
W1008 04:49:31.608353    5411 controller.go:686] retrying syncing claim "default/example-linstor-volume" because failures 0 < threshold 15
E1008 04:49:31.608391    5411 controller.go:701] error syncing claim "default/example-linstor-volume": exec: "linstor": executable file not found in $PATH:
I1008 04:49:31.631986    5411 leaderelection.go:156] attempting to acquire leader lease...
I1008 04:49:31.635261    5411 leaderelection.go:178] successfully acquired lease to provision for pvc default/example-linstor-volume
golinstor: 2018/10/08 04:49:31 linstor.go:265: ("default-example-linstor-volume"): linstor -m --controllers 192.168.10.10:8080,172.0.0.1:3366 resource-definition list
E1008 04:49:31.636864    5411 controller.go:1074] Failed to provision volume for claim "default/example-linstor-volume" with StorageClass "example-linstor-sc": exec: "linstor": executable file not found in $PATH:
I1008 04:49:31.637739    5411 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"example-linstor-volume", UID:"822f5ebe-caa4-11e8-a6cd-52540023de97", APIVersion:"v1", ResourceVersion:"749170", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass "example-linstor-sc": exec: "linstor": executable file not found in $PATH:
I1008 04:49:31.637797    5411 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"example-linstor-volume", UID:"822f5ebe-caa4-11e8-a6cd-52540023de97", APIVersion:"v1", ResourceVersion:"749170", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/example-linstor-volume"

**Comment by selvakumarnms** [comment]
[root@master-r1c1 examples]# kubectl get pvc
NAME                     STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS         AGE
example-linstor-volume   Pending

**Comment by haySwim** [comment]
Hi, the prerequisite components weren't really explained in the README as the documentation for LINSTOR wasn't in place at the time it was written. You can find it now at https://docs.linbit.com/docs/users-guide-9.0/#p-linstor

The LINSTOR components can be found here: https://github.com/LINBIT/linstor-client and https://github.com/LINBIT/linstor-server I believe that you'll have to build them from source.

Once you have a working LINSTOR cluster, you'll be able to point this provisioner to it's controller via the `controllers` option.

Let me know if you have success with this documentation and I'll update the README.

**Comment by haySwim** [comment]
Fixed via 5799d45
